owner = "lejre-fitness"
app = "lf-info"
primary_region = "fra"
org = "lejre-fitness"
[[vm]]
memory = "2gb"
cpu_kind = "shared"
cpus = 1

[build]
dockerfile = "docker/Dockerfile"

[env]
API_BASE_URL = "https://foreninglet.dk/api/"
API_VERSION = "version=1"
API_MEMBERS_API = "members"
API_ACTIVITIES_API = "activities"
API_RESIGNED_MEMBERS_API = "members/status/resigned"
MEMBERSHIP_KEYWORDS = "3 måneders medlemskab, 6 måneders medlemskab, 12 måneders medlemskab"
ACTIVITY_KEYWORDS = "holdtræning, personlig træning, holdtræning, personlig træning"
ENVIRONMENT_NAME = "PRODUCTION"
VERSION = "1.0.0-f70056c"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = [ "app",]

