# fly.toml app configuration file generated for lf-info-purple-moon-465 on 2025-03-08T12:12:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lf-info'
primary_region = 'fra'

[build]
  dockerfile = "docker/Dockerfile"

[env]
  API_BASE_URL="https://foreninglet.dk/api/"
  API_VERSION="version=1"
  API_MEMBERS_API="members"
  API_ACTIVITIES_API="activities"
  API_RESIGNED_MEMBERS_API="members/status/resigned"
  MEMBERSHIP_KEYWORDS="3 måneders medlemskab, 6 måneders medlemskab, 12 måneders medlemskab"
  ACTIVITY_KEYWORDS="holdtræning, personlig træning, holdtræning, personlig træning"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
